const fs = require('fs');
const path = require('path');

// Učitaj varijable iz environment-a
let envVars = {
  FIREBASE_API_KEY: process.env.FIREBASE_API_KEY || '',
  TMDB_API_KEY: process.env.TMDB_API_KEY || '',
  TMDB_BEARER_TOKEN: process.env.TMDB_BEARER_TOKEN || ''
};

// Za development, čitaj iz .env.local fajla
const envLocalPath = path.join(__dirname, '../.env.local');
if (fs.existsSync(envLocalPath)) {
  const envLocal = fs.readFileSync(envLocalPath, 'utf8');
  const lines = envLocal.split('\n');
  
  lines.forEach(line => {
    const trimmed = line.trim();
    if (trimmed && !trimmed.startsWith('#')) {
      const [key, ...rest] = trimmed.split('=');
      const value = rest.join('=').replace(/^["']|["']$/g, ''); // Remove quotes
      
      if (key && key in envVars) {
        envVars[key] = value;
      }
    }
  });
}

const envScript = `// Auto-generated environment variables
// DO NOT EDIT MANUALLY - generated by scripts/generate-env.js
window.__env__ = window.__env__ || {};
window.__env__.FIREBASE_API_KEY = "${envVars.FIREBASE_API_KEY}";
window.__env__.TMDB_API_KEY = "${envVars.TMDB_API_KEY}";
window.__env__.TMDB_BEARER_TOKEN = "${envVars.TMDB_BEARER_TOKEN}";

// DEBUG: Log kada se fajl učita
console.log('✅ env.js loaded successfully!');
console.log('Loaded env vars:', Object.keys(window.__env__).reduce((acc, key) => ({...acc, [key]: window.__env__[key] ? '***REDACTED***' : 'EMPTY'}), {}));
`;

const envFilePath = path.join(__dirname, '../src/assets/env.js');

try {
  fs.writeFileSync(envFilePath, envScript);
  console.log('✅ env.js generated successfully!');
  console.log(`   Location: ${envFilePath}`);
  console.log(`   Keys loaded from: ${fs.existsSync(path.join(__dirname, '../.env.local')) ? '.env.local' : 'Environment variables'}`);
  
  // DEBUG: Ispis generisanih vrijednosti
  console.log('\n🔍 Generated environment values:');
  console.log(`   FIREBASE_API_KEY: ${envVars.FIREBASE_API_KEY ? '✅ SET' : '❌ EMPTY'}`);
  console.log(`   TMDB_API_KEY: ${envVars.TMDB_API_KEY ? '✅ SET' : '❌ EMPTY'}`);
  console.log(`   TMDB_BEARER_TOKEN: ${envVars.TMDB_BEARER_TOKEN ? '✅ SET' : '❌ EMPTY'}\n`);
  
} catch (error) {
  console.error('❌ Error generating env.js:', error);
  process.exit(1);
}
